version: "3"
services:
  app:
    build: ./
    ports: 
    - "8080:8080"
    image: dalongrong/node-process
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
