{
 "title": "node process metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "rate(child_process_status_ok_total[1m])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(child_process_status_ok_total[1m])"
    }
   ]
  },
  {
   "title": "pending_process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "current_child_process_status_pending",
     "legendFormat": "{{instance}}--{{job}}"
    }
   ]
  },
  {
   "title": "rate(child_process_status_all_total[1m])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(child_process_status_all_total[1m])",
     "legendFormat": "{{instance}}--{{job}}"
    }
   ]
  },
  {
   "title": "child_process_status_ok_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "child_process_status_ok_total" }
   ]
  },
  {
   "title": "child_process_status_all_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "child_process_status_all_total", "legendFormat": "{{instance}}--{{job}}" }
   ]
  }
 ]
}